# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HCKitDemo' do
    pod 'AFNetworking', '~> 2.3.1'
    pod 'ReactiveCocoa', '~> 2.3.1'
    pod 'TPKeyboardAvoiding', '~> 1.2.3'
    pod 'HTDelegateProxy', '~> 1.0.1'
    pod 'libextobjc', '~> 0.4'
    pod 'SIAlertView', '~> 1.3'
    pod 'SDWebImage', '~> 3.7.0'
    pod 'FMDB', '~> 2.3'
    pod 'FMDBHelpers', '~> 0.0.7'
    pod 'BlocksKit', '~> 2.2.3'
    pod 'ViewUtils', '~> 1.1.2'
    pod 'JSONModel'
    pod 'TSMessages', '~> 0.9.9'
    pod 'SVProgressHUD', '~> 1.0'

end

target 'HCKitDemoTests' do

end

